apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: z49g9j4jl-java-springboot 
  janus-idp.io/tekton: z49g9j4jl-java-springboot
  backstage.io/kubernetes-id: z49g9j4jl-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z49g9j4jl-java-springboot
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  